name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Default Test Case
      id: default-test-case
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Default Test Case
        setup-command: ''
        command: xvfb-run gradle test
        timeout: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        DEFAULT-TEST-CASE_RESULTS: "${{steps.default-test-case.outputs.result}}"
      with:
        runners: default-test-case
